- name: apt update
  apt: update_cache=true cache_valid_time=86400
- name: apt install python3-pip
  apt:
    name: "{{ item }}"
  with_items:
    - python3-pip
    - unzip
    - git
- name: pip install ansible
  pip: name=ansible
