- name: wget https://.../terraform.zip && unzip -d /usr/local/bin terraform.zip
  unarchive:
    src: "{{ terraform_url }}"
    dest: /usr/local/bin
    mode: "0755"
    remote_src: true
    creates: /usr/local/bin/terraform
